/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOrganizationIndexRouteImport } from './routes/dashboard/organization/index'
import { Route as DashboardOrganizationOrgIdRouteRouteImport } from './routes/dashboard/organization/$orgId/route'
import { Route as DashboardOrganizationBoardBoardIdRouteRouteImport } from './routes/dashboard/organization/board/$boardId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrganizationIndexRoute =
  DashboardOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationOrgIdRouteRoute =
  DashboardOrganizationOrgIdRouteRouteImport.update({
    id: '/organization/$orgId',
    path: '/organization/$orgId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationBoardBoardIdRouteRoute =
  DashboardOrganizationBoardBoardIdRouteRouteImport.update({
    id: '/organization/board/$boardId',
    path: '/organization/board/$boardId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/organization/$orgId': typeof DashboardOrganizationOrgIdRouteRoute
  '/dashboard/organization/': typeof DashboardOrganizationIndexRoute
  '/dashboard/organization/board/$boardId': typeof DashboardOrganizationBoardBoardIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/organization/$orgId': typeof DashboardOrganizationOrgIdRouteRoute
  '/dashboard/organization': typeof DashboardOrganizationIndexRoute
  '/dashboard/organization/board/$boardId': typeof DashboardOrganizationBoardBoardIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/organization/$orgId': typeof DashboardOrganizationOrgIdRouteRoute
  '/dashboard/organization/': typeof DashboardOrganizationIndexRoute
  '/dashboard/organization/board/$boardId': typeof DashboardOrganizationBoardBoardIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/organization/$orgId'
    | '/dashboard/organization/'
    | '/dashboard/organization/board/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
    | '/dashboard/organization/$orgId'
    | '/dashboard/organization'
    | '/dashboard/organization/board/$boardId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/organization/$orgId'
    | '/dashboard/organization/'
    | '/dashboard/organization/board/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organization/': {
      id: '/dashboard/organization/'
      path: '/organization'
      fullPath: '/dashboard/organization/'
      preLoaderRoute: typeof DashboardOrganizationIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organization/$orgId': {
      id: '/dashboard/organization/$orgId'
      path: '/organization/$orgId'
      fullPath: '/dashboard/organization/$orgId'
      preLoaderRoute: typeof DashboardOrganizationOrgIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organization/board/$boardId': {
      id: '/dashboard/organization/board/$boardId'
      path: '/organization/board/$boardId'
      fullPath: '/dashboard/organization/board/$boardId'
      preLoaderRoute: typeof DashboardOrganizationBoardBoardIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrganizationOrgIdRouteRoute: typeof DashboardOrganizationOrgIdRouteRoute
  DashboardOrganizationIndexRoute: typeof DashboardOrganizationIndexRoute
  DashboardOrganizationBoardBoardIdRouteRoute: typeof DashboardOrganizationBoardBoardIdRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrganizationOrgIdRouteRoute: DashboardOrganizationOrgIdRouteRoute,
  DashboardOrganizationIndexRoute: DashboardOrganizationIndexRoute,
  DashboardOrganizationBoardBoardIdRouteRoute:
    DashboardOrganizationBoardBoardIdRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
